usb: typec: tcpi_fusb307: fix missing % in format specifier
tcpci_fusb307.c:543:29: error: data argument not used by format string
     [-Werror,-Wformat-extra-args]
      "Failed" : "Succeeded", chip->active_data_role ==
                              ^

Signed-off-by: Patrick Tjin <pattjin@google.com>
Change-Id: Ib144b14f4f1d5fbbc33b5e77d37f4c3e32da4a4f
(cherry picked from commit a13a21cd2583dba2dc21f757247171390505d768)