soc: gs201/cmucal-sfr: fix Section mismatch
When building with LTO=none getting following error.

WARNING: modpost: drivers/soc/google/cal-if/cmupmucal.o(.text+0xdb0): Section mismatch in reference from the function cmucal_get_sfr_node() to the variable .init.data:cmucal_sfr_block_list
The function cmucal_get_sfr_node() references
the variable __initdata cmucal_sfr_block_list.
This is often because cmucal_get_sfr_node lacks a __initdata
annotation or the annotation of cmucal_sfr_block_list is wrong.

WARNING: modpost: drivers/soc/google/cal-if/cmupmucal.o(.text+0xdb8): Section mismatch in reference from the function cmucal_get_sfr_node() to the variable .init.data:cmucal_sfr_block_list
The function cmucal_get_sfr_node() references
the variable __initdata cmucal_sfr_block_list.
This is often because cmucal_get_sfr_node lacks a __initdata
annotation or the annotation of cmucal_sfr_block_list is wrong.

WARNING: modpost: drivers/soc/google/cal-if/cmupmucal.o(.text+0xdc4): Section mismatch in reference from the function cmucal_get_sfr_node() to the variable .init.data:cmucal_sfr_access_list
The function cmucal_get_sfr_node() references
the variable __initdata cmucal_sfr_access_list.
This is often because cmucal_get_sfr_node lacks a __initdata
annotation or the annotation of cmucal_sfr_access_list is wrong.

WARNING: modpost: drivers/soc/google/cal-if/cmupmucal.o(.text+0xdcc): Section mismatch in reference from the function cmucal_get_sfr_node() to the variable .init.data:cmucal_sfr_access_list
The function cmucal_get_sfr_node() references
the variable __initdata cmucal_sfr_access_list.
This is often because cmucal_get_sfr_node lacks a __initdata
annotation or the annotation of cmucal_sfr_access_list is wrong.

WARNING: modpost: drivers/soc/google/cal-if/cmupmucal.o(.text+0xdd4): Section mismatch in reference from the function cmucal_get_sfr_node() to the variable .init.data:cmucal_sfr_list
The function cmucal_get_sfr_node() references
the variable __initdata cmucal_sfr_list.
This is often because cmucal_get_sfr_node lacks a __initdata
annotation or the annotation of cmucal_sfr_list is wrong.

WARNING: modpost: drivers/soc/google/cal-if/cmupmucal.o(.text+0xddc): Section mismatch in reference from the function cmucal_get_sfr_node() to the variable .init.data:cmucal_sfr_list
The function cmucal_get_sfr_node() references
the variable __initdata cmucal_sfr_list.
This is often because cmucal_get_sfr_node lacks a __initdata
annotation or the annotation of cmucal_sfr_list is wrong.

ERROR: modpost: Section mismatches detected.

Signed-off-by: Thierry Strudel <tstrudel@google.com>
Change-Id: I2be1c7f515ffbdc7d299d28c38c4eb9b92e50895